version: '3.8'

services:

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatsapp-enterprise-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_PATH: ./database/whatsapp_enterprise.sqlite
      PORT: 3001
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      WHATSAPP_SESSION_PATH: /app/sessions
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3001:3001"
    volumes:
      - ./backend/sessions:/app/sessions
      - ./backend/uploads:/app/uploads

    networks:
      - whatsapp-network

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whatsapp-enterprise-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_APP_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - whatsapp-network



volumes:

networks:
  whatsapp-network:
    driver: bridge 